server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://123.206.72.106:3306/hacker_rank_company?characterEncoding=utf-8
    username: admin
    password: 123456
  jackson:
    default-property-inclusion: non_empty
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰

logging:
  config: classpath:logback.xml

feign:
  httpclient:
    connection-timeout: 2000000
  hystrix:
    command:
      default:
        execution:
          isolation:
            strategy: SEMAPHORE
  client:
    config:
      default:
        connectTimeout: 200000
        readTimeout: 500000
        loggerLevel: none
    feignName:
      connectTimeout: 50000






